language: node_js
node_js:
- stable
before_install:
- npm config set "@fortawesome:registry" https://npm.fontawesome.com/
- secure: "FA0b9pcOLWJZ0IBXNrhHUsG+qEFRaK07BXNsffTI/HA1u4VCaNDtes/tIxbEhwLHvIkbzex0yCk8G3/n6aQJN5ssbYQMPvu6FyUvwY3VJMISEqk33LhEhfnY7h2QSzUemF/7SwkD51isPUQNZ+7CZZud9/eFYqSQyOucyw+N/DpXK+F2MH2YxEKwETGkNsAdDGX+sggCxVP7hrzfJ3ZcXuJzOadZcTS/rw52o6iV9QhqQ++MCTUJ3RVpsc2PGbvhSEa9Es1TTyUjlRqrys1QUCz5OZJZpUGQzU7zifd3fpRGwhVHwqELPlf/X9w+rHR1abIVW6h6crJTMBqhgsHaZmctu2emmEZkIbomREiSbE7is1Pkd/BvG02EAUIhino8Z8zb+vT0ftP1kRjaMWY/gNuY/NBcEbVVD2315/x5Zo1z2axYM2thQV7zF6yFKs5RAPMFZQpzSQbq8YfmH07bBJpb374xpNDMYrcgjsuo2RfyxiZoJdzIo0uIlqOZsp7GXTV8YrnB8Ki2vZ9KtBuISKyTZToMjVHw692XAlubVWjRHkWCJY2BpmzFLKVmny+4XKduLXlOiqnYk74InFshzYsdvQ7CNI3Y/4kNDS0zWJYEFZyMc4Oc2wAaT3HvpHH4YkgyRLkal8r3hDr+tRc8d63N+2S/uDW5PqHnDg/edlg="
before_script:
- curl https://install.meteor.com | /bin/sh
- export PATH=$HOME/.meteor:$PATH
cache:
  directories:
  - node_modules
script:
  - npm run lint
notifications:
  slack:
    rooms:
      secure: eVvAfABcW8AuAEx0iNQ/VwhNd5UsDEzUJDg7ChM8XKaanCa86vwmaTBRwOc3cYPW+ajnitazRwIWqq1KjE3EaVdFUZQTjon8XZLnphahVEsCwCsYgkA5S1Ox4QzSa09CL3x3IxQldMVXqIkEUGn2Q4IAVDq/+hShtTUl7Qo1PkkQcbDDf4bc02qDA04WhkXXnMGGsurOPFeqjAF6+QMWSRNhDMj7T4ABikKOYkj33lW2q4TH2bw/wS+E0r4sjFVGLexw+cZm+e219JeiFHRzjxd0wlZC6Kx2vn6tpHW2kW6KeVopHb0BvEKeHHiU2U36bF24DDC/MCNwAgp0crskgogL4TLXl8+H2/ApbD8dH1fw/If7iyHIcmiaudmo+acEi2CgjihKloqbQEmauTw9phQa/f+iEDsH8QHdZQwMZKRXMzTMo8ZNLEWvI9zGIt2o0ukN5rft0QmVV/SBBUpHipViCALnm30Vd136ea1sOl1Ruxkp6F5ZqqMs4qBKXv/umI9M7N8XlV3LF/1pCM68GpONVjUQvyUMnUID7bLqCmFrscI1YOZvwRjLN+oos6UjOKIQLQYOgbuCPSg04x0Exg/mRdvtZ8Ag71G9dybfFyQ91QTsGoXdgIx3Jdlp5WcLSsj3wysyBf7XJRWQSR+BTAUfr0Cwi5x55WuxUqQeDQw=
